### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by danstowell** [yardencsGitHub/tweetynet#213]
Hi - Thanks for publishing this code, and all its documentation too. I was wondering if there is a pretrained model that you share anywhere? I don't see it, but I may have missed it. No worries either way. I guess it depends to some extent whether you intend others to use the pretrained weights, or to retrain for themselves.

**Comment by NickleDave** [comment]
Hi @danstowell !

> Hi - Thanks for publishing this code, and all its documentation too. I was wondering if there is a pretrained model that you share anywhere? I don't see it, but I may have missed it. No worries either way.

Sorry it's a bit hidden: there's a separate README for the `article` code with a link to download pre-trained checkpoints here

https://github.com/yardencsGitHub/tweetynet/tree/master/article#4-download-datasets

> I guess it depends to some extent whether you intend others to use the pretrained weights, or to retrain for themselves.

A functioning script to directly reproduce a final result is still a WIP, partly because we're waiting for Dryad review (as in #211)

As of right now there's no easy way to finetune models with those checkpoints (see https://github.com/NickleDave/vak/issues/5) but since that is something users have asked for, will be added in the near-distant future

Does that answer your question?

**Comment by NickleDave** [comment]
Also: happy to share additional results if those exact checkpoints are not what you're looking for.
The total is ~300 GB 😬 You can also feel free to email @yardencsGitHub and me directly if you prefer: nicholdav at gmail + yardencsmail at gmail

**Comment by danstowell** [comment]
Thanks, looks good! I'll close this issue, but might come back if I hit a problem. I think I realise now that since each model is per-bird there won't be many use-cases for building on a pretrained model.

**Comment by NickleDave** [comment]
Sure thing!

You might find this relevant if it's the kind of thing you have in mind:
https://www.biorxiv.org/content/10.1101/2022.02.24.481827v2

Stay tuned for more along those lines.

Just let us know what else we can do to help.

**Comment by NickleDave** [comment]
Hi @danstowell it's been a while but just in case you're still interested, models pre-trained on 36 syllable classes from all 4 birds + a background class are available here:
* https://github.com/vocalpy/Nicholson-Cohen-SfN-2023-poster
* https://osf.io/3yv8s/

The exact dataset used is here: https://zenodo.org/records/10098250

This is part of a work in progress so look for more models along these lines.
If you have any feedback on the results shared in the above repo, we'd love to hear them
