### ISSUE TITLE
specify version 0.3.0 of vak as minimum required version in setup.py, after 0.3.0 release

### ISSUE THREAD

**Issue by yardencsGitHub** [yardencsGitHub/tweetynet#40]
We should allow a single pip install optimally

**Comment by NickleDave** [comment]
I agree that `pip install tweetynet` should just install the most recent version of `vak`.

However `vak` is currently are in pre-release.
`pip` will not install pre-release by default, so it installs the last release instead, 0.2.0

When you look at the number of changes we've made just between `0.3.0a5` and `0.3.0a6`, including bug fixes, then I hope you'll agree that it makes sense to still be in "pre-release" mode.
https://github.com/NickleDave/vak/blob/78cc5cb764302e6fc927e206ccaf2eac3e6eff5b/doc/CHANGELOG.md

A way around this would be to explicitly set a lowest minimum version in the `setup.py` file.
Right now we do not specify a version, which is why Tim got the default `pip` behavior.
https://github.com/yardencsGitHub/tweetynet/blob/b692279f73a4224b098c2d459f55ba323292d599/setup.py#L31

However I think a better solution is just to officially release version 0.3.0, especially since we are using it "in production" at this point.
There are basically 3 changes I think we should make before doing that:
- [ ] add logic for removing long silent periods to `WindowDataset.crop` method -- in the pull request you've already started
- [ ] modify `data_dir` option in config files so it can be a single directory (current behavior) or a list of directories
- [ ] add some functionality for applying "majority vote" transform to predicted annotations

I plan to finish these this weekend, the latter two will enable me to more easily finish up the "behavioral experiment" part of the Bengalese Finch section.
I will modify the [0.3.0 project](https://github.com/NickleDave/vak/projects/6) so that these are the only remaining issues, moving others to 0.4.0.
I think we should be able to release ~Monday. Then people will get the latest `vak` when they `pip install tweetynet`

**Comment by NickleDave** [comment]
fixed by 2418767
